"""empty message

Revision ID: 8b4b15cfabfc
Revises: 84c93afa5f8b
Create Date: 2024-11-06 11:46:42.557220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b4b15cfabfc'
down_revision: Union[str, None] = '84c93afa5f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', Column('email', String(255), unique=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
